### ISSUE TITLE
Can I use react-native-i18n with react-native-web-boilerplate

### ISSUE THREAD

**Issue by ableabhijeet** [agrcrobles/react-native-web-boilerplate#12]
Hi,
Can I use [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n) library with [react-native-web-boilerplate](https://github.com/agrcrobles/react-native-web-boilerplate)?
I was trying my luck with react-native-i18n library but react-native-18n import fails, RNI18n object returned as undefined.
`import I18n from 'react-native-i18n'`

Any suggestions?

**Comment by agrcrobles** [comment]
I think you should either look into how internationalization works in [react-native-web](https://github.com/necolas/react-native-web/blob/master/docs/guides/internationalization.md) or create platform specific files for that purpose.

Hope that helps.
