### ISSUE TITLE
error Found incompatible module

### ISSUE THREAD

**Issue by pradeep1991singh** [agrcrobles/react-native-web-boilerplate#13]
```
yarn install
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
error react-native-web-boilerplate@0.0.1: The engine "node" is incompatible with this module. Expected version ">=6.0.0 <7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Steps:
- Clone repo
- Tried `yarn`

Details:
- Node v8.9.1, MacOS

**Comment by pradeep1991singh** [comment]
Any specific reason for node >=6 & <7

**Comment by agrcrobles** [comment]
There is no specific reason for that, just get it to work some time ago using node LTS ( long term support ).

Feel free to send a PR to update it, or look into [react-native-web-fiber-boilerplate](https://github.com/agrcrobles/react-native-web-fiber-boilerplate) which is built for react 16.

Thanks for opening this issue!

**Comment by agrcrobles** [comment]
Great you fixed it :)
