### ISSUE TITLE
Error: Couldn't find preset "react-natve" relative to directory

### ISSUE THREAD

**Issue by lyahdav** [agrcrobles/react-native-web-boilerplate#4]
I cloned the repo, ran `npm install` and then `npm start` and I get this error:

```
ERROR in ./index.js
Module build failed: Error: Couldn't find preset "react-natve" relative to directory ...
```

This is apparently the same error that comes from the [motivation for this repo](https://github.com/necolas/react-native-web/issues/157) so I'm a bit confused.

I did have to change the package.json slightly. I changed the `babel-preset-stage-1` dependency version to:
`"babel-preset-stage-1": "6.13.0"`

It couldn't find the original `babel-preset-stage-1` version that was in the package.json.

**Comment by lyahdav** [comment]
Turns out there was a typo in the `.babelrc` file. `react-natve` instead of `react-native`. Turns out `react-native` isn't even needed in the `.babelrc`. I must have added it for some reason thinking it was needed. Oops.

**Comment by surenderkhowal** [comment]
Check in your package.json file there react-native installed correctly or not. You can also create .babelrc file in root of you project with following content:


{
  "presets": ["react-native"]
}
